-- SQL schema for blog comments (Supabase)
-- Run this in the SQL editor of your Supabase project or via psql

CREATE TABLE IF NOT EXISTS public.comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name text,
  content text NOT NULL,
  image_path text,
  moderated boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS comments_created_at_idx ON public.comments (created_at DESC);

-- Grant select/insert to anon role if you want public writes (adjust with RLS for security)
-- GRANT SELECT, INSERT ON public.comments TO anon;
